"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.textures = void 0;
var textures = [{
  id: 1,
  name: "bark",
  notes: "landscape bark",
  path: "/textures/ground/",
  file: "bark.jpg",
  uScale: 4,
  vScale: 2,
  thumb: "/img/thumb/textures/bark.jpg"
}, {
  id: 2,
  name: "grass001",
  notes: "A lawn",
  path: "/textures/ground/",
  file: "grass001.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/grass001.jpg"
}, {
  id: 3,
  name: "gravel1",
  notes: "gravel",
  path: "/textures/ground/",
  file: "gravel1.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/gravel1.jpg"
}, {
  id: 4,
  name: "patio",
  notes: "Grey blockwork patio",
  path: "/textures/ground/",
  file: "patio1.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/patio1.jpg"
}, {
  id: 5,
  name: "wood",
  notes: "Wood!",
  path: "/textures/ground/",
  file: "wood.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/wood.jpg"
}, {
  id: 6,
  name: "grass002",
  notes: "Wood!",
  path: "/textures/ground/",
  file: "grass002.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/grass002.jpg"
}, {
  id: 7,
  name: "grass003",
  notes: "Wood!",
  path: "/textures/ground/",
  file: "grass003.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/grass003.jpg"
}, {
  id: 8,
  name: "grass004",
  notes: "Wood!",
  path: "/textures/ground/",
  file: "grass004.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/grass004.jpg"
}, {
  id: 9,
  name: "grass005",
  notes: "Wood!",
  path: "/textures/ground/",
  file: "grass005.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/grass005.jpg"
}, {
  id: 10,
  name: "grass006",
  notes: "Wood!",
  path: "/textures/ground/",
  file: "grass006.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/grass006.jpg"
}, {
  id: 11,
  name: "soil1",
  notes: "soil",
  path: "/textures/ground/",
  file: "soil1.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/soil1.jpg"
}, {
  id: 12,
  name: "soil2",
  notes: "soil",
  path: "/textures/ground/",
  file: "soil2.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/soil2.jpg"
}, {
  id: 13,
  name: "grey_tiles",
  notes: "texturehaven",
  path: "/textures/ground/",
  file: "grey_tiles.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/grey_tiles.jpg"
}, {
  id: 14,
  name: "sandstonetiles",
  notes: "texturehaven",
  path: "/textures/ground/",
  file: "floortiles2.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/floortiles2.jpg"
}, {
  id: 15,
  name: "bricks1",
  notes: "texturehaven",
  path: "/textures/ground/",
  file: "bricks1.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/brick1.jpg"
}, {
  id: 16,
  name: "klinkers4",
  notes: "texturehaven",
  path: "/textures/ground/",
  file: "klinkers4.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/klinkers4.jpg"
}, {
  id: 17,
  name: "cobblestone",
  notes: "texturehaven",
  path: "/textures/ground/",
  file: "cobblestone.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/cobblestone.jpg"
}, {
  id: 18,
  name: "redbrick",
  notes: "texturehaven",
  path: "/textures/ground/",
  file: "redbrick.jpg",
  uScale: 1,
  vScale: 1,
  thumb: "/img/thumb/textures/redbrick.jpg"
}];
exports.textures = textures;